// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIDju2J1ySb9TLSgMCuD-Was_qT77QBT8',
    appId: '1:1088616077746:web:88e27f77400980db622cab',
    messagingSenderId: '1088616077746',
    projectId: 'auth-login-5dc5e',
    authDomain: 'auth-login-5dc5e.firebaseapp.com',
    storageBucket: 'auth-login-5dc5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABbESsBzouxCaJK7VpMeviDAW5aOg-_N4',
    appId: '1:1088616077746:android:69b9369be16f2d53622cab',
    messagingSenderId: '1088616077746',
    projectId: 'auth-login-5dc5e',
    storageBucket: 'auth-login-5dc5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlku8dQk82O08Qx3aSwg3nnLW2skNzgRQ',
    appId: '1:1088616077746:ios:e889fd3c08579c5a622cab',
    messagingSenderId: '1088616077746',
    projectId: 'auth-login-5dc5e',
    storageBucket: 'auth-login-5dc5e.firebasestorage.app',
    iosBundleId: 'com.example.loginModernUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlku8dQk82O08Qx3aSwg3nnLW2skNzgRQ',
    appId: '1:1088616077746:ios:e889fd3c08579c5a622cab',
    messagingSenderId: '1088616077746',
    projectId: 'auth-login-5dc5e',
    storageBucket: 'auth-login-5dc5e.firebasestorage.app',
    iosBundleId: 'com.example.loginModernUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIDju2J1ySb9TLSgMCuD-Was_qT77QBT8',
    appId: '1:1088616077746:web:c2531a5082a0f265622cab',
    messagingSenderId: '1088616077746',
    projectId: 'auth-login-5dc5e',
    authDomain: 'auth-login-5dc5e.firebaseapp.com',
    storageBucket: 'auth-login-5dc5e.firebasestorage.app',
  );
}
